### ISSUE TITLE
Running triangle_rpi4.c does not require HDMI connection

### ISSUE THREAD

**Issue by hulloanson** [matusnovak/rpi-opengl-without-x#11]
I'm running Buster on RPI4

Some info:
```
$ uname -a
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
$ cat /proc/cpuinfo
...
Hardware	: BCM2711
Revision	: c03112
Model		: Raspberry Pi 4 Model B Rev 1.2
```
Steps followed:
1. `sudo apt-get install libegl1-mesa-dev libgbm-dev libgles2-mesa-dev libdrm-dev -y`
2. `git clone https://github.com/matusnovak/rpi-opengl-without-x && cd rpi-opengl-without-x`
3. `gcc -o triangle_rpi4 triangle_rpi4.c -ldrm -lgbm -lEGL -lGLESv2 -I/usr/include/libdrm -I/usr/include/GLES2`
4. Execute, no X server, no HDMI output connected.
```
$./triangle_rpi4 
resolution: 1680x720
Initialized EGL version: 1.4
GL Viewport size: 1680x720
```

**Comment by matusnovak** [comment]
Hi @hulloanson 

Thank you for this information. I must have done something wrong in my setup that required a hdmi output. I am glad I was wrong.

I will update the Readme.

**Comment by toothlessblue** [comment]
My Pi4B would not run the program on a fresh Debian Lite install, following the instructions in the readme, I also had to add to `/boot/firmware/cmdline.txt` - `vc4.force_hotplug=1 drm.edid_firmware=HDMI-A-1:1920x1080M@60`

---
5/6 years later and I'm using this repo for a project, vulkan's probably the better option for the use case at this point but I'm familiar with OpenGL
