### ISSUE TITLE
Double buffer issue

### ISSUE THREAD

**Issue by gitbf** [matusnovak/rpi-opengl-without-x#7]
Thanks for sharing the RPI4 example - much appreciated!

The "gbmSwapBuffers" function uses two independent buffers.  This is all clever as it prevents disturbance/flickering while preparing/rendering the next screen. The fact that these buffers are alternating however is also creating an issue. When only parts of a screen needs updating, you want to leave everything else untouched. 

The way the two buffers are used cause the display to mix new and old content. Another approach is to make sure every refresh cycle starts with the latest content.

Do you see a way to make sure the background buffer used for rendering inherits whatever was displayed during the previous refresh/redraw cycle?

The examples below show how the display keeps alternating whenever I redraw the left part only. The right part is a leftover only present in one of the two buffers. It may seem obvious to just redraw everything, but this  may not be trivial for applications that rely on buffer content being preserved.

![image](https://user-images.githubusercontent.com/12115023/69012713-26827c80-0979-11ea-87b8-b8e42d10a609.png)

![image](https://user-images.githubusercontent.com/12115023/69012619-1fa73a00-0978-11ea-8822-b07eaa075f95.png)

**Comment by matusnovak** [comment]
hi @gitbf 

I am not the author of the double buffer mechanism, that credit goes to here: https://github.com/eyelash/tutorials/blob/master/drm-gbm.c

But I understand your problem, I had the same issue when I was working on a similar project. I have two solutions:

- Option A, render everything into an OpenGL framebuffer (or renderbuffer). You can still use double buffering for the final output, but your GUI will be rendered into separate framebuffer/renderbuffer. You will essentially have a single off-screen buffer. Even at full HD resolution, the extra framebuffer should only occupy 6.2MB of GPU memory. You can then have two choices to copy the framebuffer to the screen (to the backbuffer):
  - Via [glBlitFramebuffer](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glBlitFramebuffer.xhtml), but that's only available if you replace `EGL_OPENGL_ES2_BIT` with `EGL_OPENGL_ES3_BIT` (`glBlitFramebuffer` is only available in OpenGL ES 3), but I have not tested it personally.
  - Via a shader program. Simply load the framebuffer attachment (the RGB texture) into a shader program, and render it onto a full-screen quad polygon. I can walk you through it.
- Option B, don't use double buffering at all. You can force single buffering by adding `EGL_RENDER_BUFFER, EGL_SINGLE_BUFFER,` to the [configAttribs on line 142 in triangle_rpi4.c](https://github.com/matusnovak/rpi-opengl-without-x/blob/master/triangle_rpi4.c#L142) and not using `gbmSwapBuffers` at all. But I can not guarantee it will work. I was only able to get this (single buffer mode) working on Raspberry Pi 3.

I recommend the framebuffer option.

edit: Should have been: "replace `EGL_OPENGL_ES2_BIT` with `EGL_OPENGL_ES3_BIT`", not the other way around.

**Comment by gitbf** [comment]
Thanks, I'll give it a try.
