### ISSUE TITLE
Pi4 with LCD output has no vsync

### ISSUE THREAD

**Issue by ArtArt0** [matusnovak/rpi-opengl-without-x#9]
On Pi3 it has the correct 60 FPS, but Pi4 i can more than 60 (LCD refresh is especially 60Hz).

If I do the same on HDMI, it is OK, no more than 60 FPS happens.

I use the same gbmSwapBuffers...

**Comment by matusnovak** [comment]
Hi @ArtArt0 

Do you mean this function https://github.com/matusnovak/rpi-opengl-without-x/blob/master/triangle_rpi4.c#L104 ? `gbmSwapBuffers(EGLDisplay *display, EGLSurface *surface)` ?

Are you passing the correct displays and surfaces into the function? I assumme you have two `EGLDisplay` variables. 

Also, try using `eglSwapInterval` function ([docs here](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglSwapInterval.xhtml)). You only need to call it once (once per `EGLDisplay`) at the beginning with a parameter `interval=1`. (1 = vsync enabled). I am not exactly sure how it will behave on Raspberry Pi 4 but it may help.

**Comment by ArtArt0** [comment]
H!

Yes, that function.
I think so. Yes I have 2.

I think `eglSwapInterval` is not what we need, rather the `drmModePageFlip`.
Also not needed always `drmModeAddFB`...

Anyway the default swap interval is 1, so because I did not set it, vsynk should be work, but it does not (FPS > 60)

**Comment by matusnovak** [comment]
I am afraid I am out of ideas. I haven't encountered this problem before.

**Comment by ArtArt0** [comment]
OK, thanx, I am trying...

**Comment by jvcleave** [comment]
@ArtArt0 may i ask how you are measuring the frame rate?

**Comment by ArtArt0** [comment]
I just count the drawing cycle and print if the second of the time changes.

**Comment by ArtArt0** [comment]
So, I can make vsync with `drmModePageFlip` and it perfectly works on one display.
(interesting fact that my HDMI has 60FPS, but the original official 7'' LCD has 67-68 (Pi4 only, because on Pi3 it has 60 as well))

But if I use 2 displays, the second `drmModePageFlip` call blocks, and I can not get the other callback in time, soin this mode my FPS is 30 (needed 60).

I tried it in Ubuntu environment (virtualbox 2 monitors), and it is the same.

The delay I think should be during the `select(fd, ...)`, not during `drmModePageFlip`...

**Comment by ArtArt0** [comment]
I tested my code on a nativ Ubuntu (dual display) (virtual machines are not good for testing vsync), and it worked successfully.
So the `select` is waiting as I espect, and not the `drmModePageFlip`.
On Rpi4, `select` is waiting (if it has to) and `drmModePageFlip` too as well!
The next `select `of course usually does not wait, because the next vsync happened before and the file handler is readable.

So I think the `drmModePageFlip` in the kernel is buggy on Rpi4...

**Comment by matusnovak** [comment]
I will close this as the conversation has not progressed since.
